[data]
directory = "~/.local/share/xmpp-p2p-bob"

[connection]
default_transport = "direct-p2p"
api_host = "127.0.0.1"
api_port = 8766

[p2p]
local_jid = "bob@p2p.local"
listen_host = "127.0.0.1"
listen_port = 5224

[security]
allow_self_signed_direct = true
